---
  - name: enable root login
    ansible.builtin.lineinfile: 
      path: /etc/ssh/sshd_config 
      regexp: '^PermitRootLogin yes'
      line: PermitRootLogin yes
      state: present

  - name: Restart sshd
    ansible.builtin.service:
      name: sshd
      state: restarted

